version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    ports:
      - 8080:8000
    networks:
      - proxy-tier
    environment:
      - VIRTUAL_HOST=<host>
      - VIRTUAL_PORT=9000
      - LETSENCRYPT_HOST=<host>
      - LETSENCRYPT_EMAIL=<email>
networks:
  proxy-tier:
    external: true
